###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Nature",
    "author": "Kiriko",
    "url": "https://ilovemaths.fi",
    "likes": 50
}


###
GET http://localhost:3003/api/blogs